controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
puesto_nuevo:
    path: /puesto/nuevo
    controller: App\Controller\PuestoController::nuevo

puesto_exito:
    path: /puesto/exito
    controller: App\Controller\PuestoController::exito
